# docker-compose.yml
version: '2.1'

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    depends_on:
      - craft
    volumes_from:
      - craft
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf # nginx configuration (see below)
      - ./assets:/var/www/public_html/assets # For assets
      - ./app:/var/www/public_html/app # For static assets (media, js and css). We don't need PHP for them.

  craft:
    image: urbantrout/craftcms:mysql
    depends_on:
      - mariadb
    volumes:
      - ./backups:/var/www/public_html/storage/backups
      - ./templates:/var/www/public_html/templates # Craft CMS template files
      - ./modules:/var/www/public_html/modules # Craft modules directory
      - ./config/element-api.php:/var/www/public_html/config/element-api.php # Element API file - we require the plugin below
    environment:
      DEPENDENCIES: >- # additional composer packages (must be comma separated)
        barrelstrength/sprout-encode-email,
        barrelstrength/sprout-fields,
        craftcms/redactor,
        craftcms/aws-s3,
        craftcms/element-api,
        fruitstudios/linkit, 
        mmikkel/cp-clearcache,
        nystudio107/craft-seomatic,
        nystudio107/craft-imageoptimize,
        nystudio107/craft-minify,        
        superbig/craft3-http2serverpush,
        verbb/navigation,
        verbb/super-table,
        yiisoft/yii2-redis

      CRAFTCMS_EMAIL: rob@e2design.nl
      CRAFTCMS_USERNAME: eeadmin
      CRAFTCMS_PASSWORD: password
      CRAFTCMS_SITENAME: Boilerplate
      CRAFTCMS_LANGUAGE: en

      REDIS_HOST: redis
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis

      DB_SERVER: mariadb
      DB_NAME: craft
      DB_USER: craft
      DB_PASSWORD: secret
      DB_DATABASE: craft
      DB_SCHEMA: public
      DB_DRIVER: mysql
      DB_PORT: 3306

  mariadb:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: craft
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: craft
    volumes:
      # Persistent data
      - dbdata:/var/lib/mysql

  redis:
    image: redis:4-alpine
    volumes:
      - redisdata:/data

volumes:
  dbdata:
  redisdata:
